name: punycoder
description: Punycoder is a well tested Dart implementation of the RFC 3492 Punycode specification
version: 0.3.0
repository: https://github.com/dropbear-software/punycoder/
issue_tracker: https://github.com/dropbear-software/punycoder/issues
topics:
  - punycode
  - standards
  - internationalisation
  - unicode
  - codec

environment:
  sdk: ^3.7.2

dev_dependencies:
  lints: ^6.1.0
  test: ^1.24.0
